### ISSUE TITLE
[VOTE] Ensure no unused imports and useless aliases

### ISSUE THREAD

**Issue by ronan-gloo** [shoppingflux/coding-style-php#12]
### Summary

- Import with keyword `use` not used in the current fields should be cleaned
- Import with aliases having the same same that the qualified class should be cleaned

### Invalid Example

```php
<?php
namespace Sf;

# The import is never used
use Vendor\Object;

# The alias is same as the orignal classname
use Vendor\Class as Class;

function test(Class $arg) {
}
```

### Valid Example

```php
<?php
namespace Sf;

# The import is used and alias differ
use Vendor\Class as Object;

function test(Object $arg) {
}
```

### Rule declaration

According [the installation of the following extensions](https://github.com/slevomat/coding-standard#slevomatcodingstandardnamespacesunuseduses-)

```
composer require slevomat/coding-standard
```

Rules declaration will be 

```
<config name="installed_paths" value="../../slevomat/coding-standard"/>
<rule ref="SlevomatCodingStandard.Namespaces.UnusedUses"/>
<rule ref="SlevomatCodingStandard.Namespaces.UselessAlias"/>
```

**Comment by mdumoulin** [comment]
Ok pour moi.

**Comment by ronan-gloo** [comment]
@shoppingflux/devs ping

**Comment by ddattee** [comment]
Ok pour moi

**Comment by budrea** [comment]
👍
