### ISSUE TITLE
[VOTE] Uniformiser la façon de récupérer 1 ou plusieurs éléments en utilisant le Criteria

### ISSUE THREAD

**Issue by budrea** [shoppingflux/coding-style-php#14]
### Summary

Dans la documentation de la partie de lecture que @ronan-gloo a rédigé ici : 
https://github.com/shoppingflux/ddd/blob/master/docs/read.md#read-repository

, dans la partie exemple, on doit d’uniformiser la façon de récupérer 1 ou plusieurs éléments en utilisant le Criteria. 

Les propositions sont : 
1. fetch one item `fetchBy(CriteriaInterface $criteria): ReadModel;`, fetch multiple items `fetchAllBy(CriteriaInterface $criteria): \Traversable;`

2. fetch one item `fetchOneBy(CriteriaInterface $criteria): ReadModel;`, fetch multiple items `fetchBy(CriteriaInterface $criteria): \Traversable;`

Suite à une discussion  sur slack, c'est l'option 2 qui fait unanimité, du coup je vais l'utiliser dans l'exemple ci-dessous? 

- Specific Constraint explanation 
- Other Constraint explanation

### Valid Code

```php
<?php
namespace ShoppingFeed\ExampleDomain\Read

interface ExampleDomainAccessInterface
{
    public function fetchOneBy(CriteriaInterface $criteria): ReadModel;

    public function fetchBy(CriteriaInterface $criteria): \Traversable;
}
```

### Invalid Code

```php
<?php
namespace ShoppingFeed\ExampleDomain\Read

interface ExampleDomainAccessInterface
{
    // or any other variation
    public function fetchBy(CriteriaInterface $criteria): ReadModel;

    // or any other variation
    public function fetchAllBy(CriteriaInterface $criteria): \Traversable;
}
```

**Comment by ronan-gloo** [comment]
@budrea pour les tags, c'est soit une recommendation soit un pre-requis, mais pas les deux :)

**Comment by ronan-gloo** [comment]
Est-ce que l'on ne devrait pas aller plus loin et toujours demander un paginator adapter dans le fetchAllBy() ? C'est le cas nominal d'utilisation dans les API, d'avoir des résultats paginés. 


```php
<?php
namespace ShoppingFeed\ExampleDomain\Read

interface ExampleDomainAccessInterface
{
    public function fetchOneBy(CriteriaInterface $criteria): ReadModel;

    public function fetchBy(CriteriaInterface $criteria): \ShoppingFeed\Paginator\PaginatorAdapterInterface;
}
```

Sinon je serais pour un mix des deux (le relou quoi !)
- fetchOneBy
- fetchAllBy

**Comment by budrea** [comment]
- ok pour le Paginator
- pour le mix des 2, ça a le mérite d'être clair (on sait combien on fetch, c'est dans le nom, du coup je suis pour aussi)

**Comment by budrea** [comment]
@mdumoulin , @ddattee , @olivierh94 - un avis ?

**Comment by mdumoulin** [comment]
Ça me va.

**Comment by budrea** [comment]
Du coup, on reste sur du :
```
// je viens de le rajouter, mais la plupart du temps on a un fetch direct aussi avec l'id, pour simplifier l'appel; on le garde
public function fetch(int $id): ReadModel;

public function fetchOneBy(CriteriaInterface $criteria): ReadModel;

public function fetchAllBy(CriteriaInterface $criteria): \Traversable;
```

**Comment by ronan-gloo** [comment]
L'ensemble serait plus consistent d'appeler `fetch` en `fetchOne`.

**Comment by ddattee** [comment]
Ok pour moi avec le paginator

**Comment by ronan-gloo** [comment]
Ok pour moi aussi

**Comment by olivierh94** [comment]
bon ca date un peu, mais ok pour moi, donc pour resumé

**Comment by ddattee** [comment]
Ok pour moi pour le dernier exemple de bogdan.

**Comment by ddattee** [comment]
Proposition discuté vdd 22/11 avec @mdumoulin @olivierh94 @ddattee @yvanngn : 
```
fetch(int $id): ReadModel;
fetchBy(Criteria $criteria): ReadModel;
fetchAllBy(Criteria $criteria): Paginator;
```

**Comment by budrea** [comment]
@ddattee j'ai mis à jour [la PR](https://github.com/shoppingflux/coding-style-php/pull/15), merci pour la clarification. Je ferme l'issue.
