### ISSUE TITLE
[VOTE] Use simple quote there is nothing to interpret in the string

### ISSUE THREAD

**Issue by mdumoulin** [shoppingflux/coding-style-php#18]
### Summary

- Always use single quote « ' » when the content does not require any interpretation

### Code Example

```php
<?php

# Valid
$hello = 'Hello world !';
$anotherString = "I said : $hello";

# Invalid
$hello = "Hello world !";
$address = $data[0]["address"];
```

**Comment by ddattee** [comment]
C'est pas déja en place ca ? J'ai des warnings chez moi mais ce n'est peut etre que mon IDE.
