### ISSUE TITLE
[VOTE] Never use '&' when providing object to a method

### ISSUE THREAD

**Issue by mdumoulin** [shoppingflux/coding-style-php#19]
### Summary

- Objects are always passed by reference. Using '&' to request to pass it by reference can be confusing

### Code Example

```php
<?php

# Valid
function dataDiff(\DateTime $firstDate, \DateTime $secondDate): \DateInterval
{
    return $firstDate->diff($secondDate);
}

# Invalid
function dataDiff(\DateTime &$firstDate, \DateTime &$secondDate): \DateInterval
{
    return $firstDate->diff($secondDate);
}
```

**Comment by ronan-gloo** [comment]
@mdumoulin On a une règle pour vérifier ça ?

**Comment by mdumoulin** [comment]
Non, je n'en ai pas trouvé de prêt à l'emploi.

**Comment by ronan-gloo** [comment]
Faut donc l'ajouter aux recommendations https://github.com/shoppingflux/coding-style-php/blob/master/docs/style.md
