### ISSUE TITLE
[VOTE] Classes names should be valid

### ISSUE THREAD

**Issue by ronan-gloo** [shoppingflux/coding-style-php#24]
### Summary

- Check that the class declaration adheres to all PSR2 rules
- Class and interface names must start with a capital letter for each part of the name

### Code Example

```php
<?php

# Valid
class ClassName {}

# Invalid
class classname {}
```

### Rule declaration

```
<rule ref="PEAR.NamingConventions.ValidClassName"/>
<rule ref="PSR2.Classes.ClassDeclaration"/>
```

**Comment by ronan-gloo** [comment]
Example of missed rule https://github.com/shoppingflux/shoppingflux/pull/5226/files#diff-4da901fbda95b5c8b62cd49c1d8aa9ecR4

**Comment by ronan-gloo** [comment]
@shoppingflux/devs ready for vote

**Comment by mdumoulin** [comment]
Tu es sûr que la règle PEAR ajoute quelque chose ? J'ai l'impression qu'elle gère les nommages à l'ancienne (avant namespace) ?
Ex.: 'ShoppingFeed_Channel_Import'

Sinon, ok sur le principe.

**Comment by ronan-gloo** [comment]
Elle gère aussi les majuscules.

**Comment by ronan-gloo** [comment]
@shoppingflux/devs ok ?
