### ISSUE TITLE
[VOTE] Domain event organization

### ISSUE THREAD

**Issue by mdumoulin** [shoppingflux/coding-style-php#25]
### Summary

This vote aims to define the way to organize events inside the domain layer. Please share yours propositions before the final vote. I will add it in the description.

### Option 1

Domain events are directly in the Domain directory.

- ShoppingFeed\Order\Domain\AcknowledgedEvent
- ShoppingFeed\Order\Domain\BilingAddress
- ShoppingFeed\Order\Domain\OperationCompleteEvent
- ShoppingFeed\Order\Domain\Order
- ShoppingFeed\Order\Domain\OrderAddress
- ShoppingFeed\Order\Domain\UnacknowledgedEvent

### Option 2

Domain events are under an Event sub-directory and not suffixed by Event

- ShoppingFeed\Order\Domain\Event\Acknowledged
- ShoppingFeed\Order\Domain\Event\OperationComplete
- ShoppingFeed\Order\Domain\Event\Unacknowledged
- ShoppingFeed\Order\Domain\BilingAddress
- ShoppingFeed\Order\Domain\Order
- ShoppingFeed\Order\Domain\OrderAddress

### Option 3

Domain events are under an Event sub-directory and suffixed by Event

- ShoppingFeed\Order\Domain\Event\AcknowledgedEvent
- ShoppingFeed\Order\Domain\Event\OperationCompleteEvent
- ShoppingFeed\Order\Domain\Event\UnacknowledgedEvent
- ShoppingFeed\Order\Domain\BilingAddress
- ShoppingFeed\Order\Domain\Order
- ShoppingFeed\Order\Domain\OrderAddress

**Comment by ddattee** [comment]
I vote for 2 or 3

**Comment by mdumoulin** [comment]
S'il n'y a pas d'autres propositions. Je voterai 2. Pour moi plus clair de regrouper tous les événements ensemble et le suffixe est inutile car j'aurai tendance à écrire les choses comment ça dans le code pour minimiser le nombre d'import :

```php
// In Order domain namespace
namespace ShoppingFeed\Order\Domain;

Event\Acknowledged::create(...);
Event\Unacknowledge::create(...);

// In another namespace
namespace ShoppingFeed\Whatever;
 
use ShoppingFeed\Order\Domain\Event as OrderEvent;

OrderEvent\Acknowledged::create(...);
OrderEvent\Unacknowledge::create(...);
```

**Comment by yvanngn** [comment]
A l'usage,  j'aurai plutôt opté pour la 3 parce que beaucoup de fichier dans des namespaces vont avoir le même nom et je cherche souvent un fichier par son nom, du coup si j'ai plus d'infos sur lui c'est plus simple.

**Comment by mdumoulin** [comment]
> A l'usage, j'aurai plutôt opté pour la 3 parce que beaucoup de fichier dans des namespaces vont avoir le même nom et je cherche souvent un fichier par son nom, du coup si j'ai plus d'infos sur lui c'est plus simple.

Le problème que tu évoques concerne les 3 options proposées d'après moi. Pour l'éviter, il faudrait ajouter le contexte du domaine dans le nom de l'événement :  'ShoppingFeed\Order\Event\OrderCreated'

PhpStorm est assez malin pour retrouver les classes. À vérifier, mais je pense que si tu fais une recherche de classe 'OrderCreated', il retrouvera 'Order\Event\Created'.

Si tu veux on peut ajouter une proposition. Il faudrait juste que tu la formules en utilisant le même exemple que les 3 autres options stp.

**Comment by yvanngn** [comment]
Non non pas la peine de rajouter une proposition pour moi. Si PHPStorm permet de gérer toutes les options j'ai pas plus d'objections que ca.

**Comment by olivierh94** [comment]
Je suis pour l'option 2

**Comment by budrea** [comment]
Option 2 pour moi aussi.

**Comment by ronan-gloo** [comment]
Option 1 pour moi, c'est ce que l'on fait déjà dans la grande majorité des cas, et ça me paraît être un coup assez cher (aka migrer tous les composants) pour un intêret discutable.
Ceci dit ça vaudrait le coup d'argumenter la proposition.

Je tiens juste à rappeler que en fonction de ce que l'on choisi, cela implique une mise à niveau des composants, donc un refacto non négligeable. On est pas en train de discuter de quelque chose d'uniquement théorique. ça pèse fortement sur la décision selon moi.

**Comment by mdumoulin** [comment]
En fait, c'est un peu le bazarre, on a un peu de tout. D'où l'intérêt de se décider.

Mais côté API, on a plutôt une majorité de composant avec un répertoire Event :
- Account
- Channel
- Feed
- Order
- Order tag
- Timeline

Les composant sans :
- Catalog Inventory
- Catalog Pricing
- Store

Ça me semble important de préciser, si les événements doivent répéter le nom du domaine lorsqu'il le concerne directement. Le cas n'est pas visible pris sur l'exemple Order, je prends donc un autre exemple.

- Catalog\Event\Created
- Catalog\Event\Removed
- Catalog\Event\ProductAdded
- Catalog\Event\ProductRemoved

Ou 

- Catalog\Event\CatalogCreated
- Catalog\Event\CatalogRemoved
- Catalog\Event\ProductAdded
- Catalog\Event\ProductRemoved

J'ai mis l'exemple avec l'option 2. mais la règle peut-être déclinée sur n'importe laquelle des options proposées.

**Comment by olivierh94** [comment]
@mdumoulin on devait pas faire un point la dessus ?

**Comment by mdumoulin** [comment]
Comme je disais ce matin en DSM. Je vais élargir la discussion à l'organisation globale du répertoire Domain.
Je ferme cette issue. Je vous partagerai qqc sous peu, mais peut-être via un autre moyen qu'une issue github.
