### ISSUE TITLE
[VOTE] Single line method params unless max line chars is reached

### ISSUE THREAD

**Issue by ronan-gloo** [shoppingflux/coding-style-php#26]
### Summary

Depending developers and mood, method declaration sometimes jump lines.
To get more consistency in methods declaration than today, i propose:

- Do not arbitrary jump lines in method declaration  
- Only jump lines when max line chars is reached

### Valid Code

```php
<?php

// Desired declaration
public function handle(ServerRequestInterface $request, ServerHandlerInterface $handler): void
{
}

```
### Invalid Code

```php
<?php

// Max line chars was not reached, we should not jump lines between params
public function handle(
    ServerRequestInterface $request,
    ServerHandlerInterface $handler): void
{
}
```

**Comment by ddattee** [comment]
I would add : on multi line output typehint should be on a new line.

**Valid**
```php
<?php

// Max line chars was not reached, we should not jump lines between params
public function handle(
    ServerRequestInterface $request,
    ServerRequestInterface $request2,
    ServerRequestInterface $request3,
    ServerHandlerInterface $handler
): void
{
}
```

**Unvalid**
```php
<?php

// Max line chars was not reached, we should not jump lines between params
public function handle(
    ServerRequestInterface $request,
    ServerRequestInterface $request2,
    ServerRequestInterface $request3,
    ServerHandlerInterface $handler): void
{
}
```

**Comment by mdumoulin** [comment]
J'allais dire la même chose que David, il faudrait aussi se mettre d'accord sur le format du multi-line des déclarations de fonctions.

**Comment by ronan-gloo** [comment]
D'accord aussi. Ceci dit c'est un autre sujet en fait, et je pense que l'on doit avoir une règle phpcs dispo pour ça. Je vous laisse ouvrir une proposition, ça serait clairement bien

**Comment by ddattee** [comment]
Proposition transférée : https://github.com/shoppingflux/coding-style-php/issues/27

**Comment by ronan-gloo** [comment]
@ddattee Ca ne parle pas de la même chose
