### ISSUE TITLE
[VOTE] Force one line documentation comment for class properties

### ISSUE THREAD

**Issue by mdumoulin** [shoppingflux/coding-style-php#46]
### Summary

- Force one line documentation comment for class properties

### Code Example

```php
<?php

# Valid
class Product
{
    /** @var Variation[] */
    private array $variations;
}

# Invalid
class Product
{
    /**
     * @var Variation[]
     */
    private array $variations;
}
```

### Example
Apply rule on API : https://github.com/mdumoulin/api/pull/16/files

### Rule declaration

```
 <rule ref="SlevomatCodingStandard.Commenting.RequireOneLinePropertyDocComment.MultiLinePropertyComment"/>
```

**Comment by ronan-gloo** [comment]
Donc on ne pourra plus documenter les propriétés avec du texte si besoin ?

**Comment by mdumoulin** [comment]
Non, ça n'impacte que les commentaires sur une seule ligne. J'ai trouvé quelques exemples dans la PR montrant que les commentaires multiligne sont sont préservés :

- https://github.com/mdumoulin/api/pull/16/files#diff-4cfe24ffdb217b0258ecf526dda5a236f01a35183859d3601fe81e14b68843e5L32
- https://github.com/mdumoulin/api/pull/16/files#diff-ecb43d34474a0311d04943119c3f568eb5bc76c424ca69c7049d13a16ff62c06R97
