### ISSUE TITLE
[VOTE] No empty line after class declaration

### ISSUE THREAD

**Issue by KevinFrydman** [shoppingflux/coding-style-php#53]
### Summary

- No empty line after class declaration

### Code Example

```php
<?php

# Valid
class MyClass
{
    public function myFunction()
    {
    }
}

# Invalid
class MyClass
{


    public function myFunction()
    {
    }
}
```

### Rule declaration

```
 <rule ref="PSR12.Classes.OpeningBraceSpace" />
```

Thread found here https://github.com/squizlabs/PHP_CodeSniffer/issues/3437

**Comment by mdumoulin** [comment]
Cette règle devrait déjà être appliquée normalement. Toutes les règles de la PSR12 sont dans le CS.

**Comment by KevinFrydman** [comment]
Ok, my bad, on les a dans les TU mais pas dans le reste du projet mais oui, déja prise en compte

**Comment by mdumoulin** [comment]
Sur l'API, on a fait le choix d'ajouter les CS sur les TU il y a quelques temps.
