### ISSUE TITLE
[VOTE] No whitespace between use

### ISSUE THREAD

**Issue by KevinFrydman** [shoppingflux/coding-style-php#55]
### Summary

- No whitespace between use

### Code Example

```php
<?php

# Valid
use Throwable;
use function GuzzleHttp\json_decode;

# Invalid
use Throwable;

use function GuzzleHttp\json_decode;
```

### Rule declaration

```
<rule ref="SlevomatCodingStandard.Namespaces.UseSpacing"/>
```

**Comment by mdumoulin** [comment]
Je suis plutôt contre car ça viole une des règles PSR12 qui veut qu'il y ai un saut de ligne entre les use de classe, de fonction et de const : https://www.php-fig.org/psr/psr-12/

**Comment by Aurelieluciani** [comment]
D'accord avec Martin pour les mêmes raisons

**Comment by KevinFrydman** [comment]
Aucun soucis
